version: '3'
services:
  node1:
    image: 'p2pnetasio:latest'
    volumes:
      - ./config1.json:/app/config.json
      - ./build/bin/p2p-test:/app/p2p-test
      - ./start.sh:/start.sh
    command: bash start.sh 
    privileged: true
    ports:
      - 5555:5555
    # network_mode: host
    networks:
      custom_network:
        ipv4_address: 172.18.0.2
  node2:
    image: 'p2pnetasio:latest'
    volumes:
      - ./config2.json:/app/config.json
      - ./build/bin/p2p-test:/app/p2p-test
      - ./start.sh:/start.sh
    command: bash start.sh 
    privileged: true
    ports:
      - 5556:5556
    networks:
      custom_network:
        ipv4_address: 172.18.0.3

  # node3:
  #   image: 'p2pnetasio:latest'
  #   volumes:
  #     - ./config2.json:/app/config.json
  #     - ./build/bin/p2p-test:/app/p2p-test
  #     - ./start.sh:/start.sh
  #   command: bash start.sh 
  #   privileged: true
  #   ports:
  #     - 5556:5556
  #   networks:
  #     custom_network:
  #       ipv4_address: 172.18.0.4

  # node3:
  #   image: 'ubuntu:latest'
  #   volumes:
  #     - ./config3.json:/app/config.json
  #     - ./build/bin/p2p-test:/app/p2p-test
  #     # - ./config2.json:/app
  #   # command: ls /app
  #   command: ./app/p2p-test ./app/config.json
  #   ports:
  #     - 5557:5557
  #   # depends_on:
  #     # - node2
  #   network_mode: host

networks:
  custom_network:
    driver: bridge 
    # ipam:
    #   config:
    #     - subnet: 172.18.0.0/16