# Dockerfile-tc for node1
FROM ubuntu:latest

RUN apt-get update && apt-get install -y iproute2

# Define the network conditions, e.g., limiting bandwidth to 1 Mbps
# CMD tc qdisc add dev eth0 root tbf rate 1mbit burst 10b latency 50000ms