version: '3'
services:
  node1:
    image: 'ubuntu:latest'
    # build:
      # context: ./
    #   dockerfile: Dockerfile
    volumes:
      - ./config1.json:/app/config.json
      - ./build/bin/p2p-test:/app/p2p-test
      # - ./config2.json:/app
    # command: ls /app
    command: ./app/p2p-test ./app/config.json
    ports:
      - 5555:5555
    network_mode: host
    # networks:
      # - my_network
  node2:
    image: 'ubuntu:latest'
    volumes:
      - ./config2.json:/app/config.json
      - ./build/bin/p2p-test:/app/p2p-test
      # - ./config2.json:/app
    # command: ls /app
    command: ./app/p2p-test ./app/config.json
    ports:
      - 5556:5556
    # depends_on:
      # - node1
    network_mode: host
    # networks:
      # - my_network
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # command: ["./build/bin/node-network", "config2.json"]
  node3:
    image: 'ubuntu:latest'
    volumes:
      - ./config3.json:/app/config.json
      - ./build/bin/p2p-test:/app/p2p-test
      # - ./config2.json:/app
    # command: ls /app
    command: ./app/p2p-test ./app/config.json
    ports:
      - 5557:5557
    # depends_on:
      # - node2
    network_mode: host
  # node3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["./node", "config_node3.json"]
  # node4:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["./node", "config_node4.json"]

# networks:
  # my_network:
